spring:
  security:
    user.name: admin # Default user name.
    user.password: admin # Password
  datasource:
    url: jdbc:h2:mem:libraryDB
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#  #    show-sql: true
#  #    properties:
#  #      hibernate:
#  #        format_sql: true
#  h2:
#    console.enabled: true
#    path: /h2-console


server:
  port: 8000
